spring:
  config:
    activate:
      on-profile: local

  datasource:
    url: jdbc:postgresql://${DB_LOCAL_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:user_service_db}
    username: ${DB_USERNAME:javauser}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081

logging:
  level:
    com.innowise.userservice: DEBUG